version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 590184014967.dkr.ecr.eu-west-1.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t portfolio-app .
      - docker tag portfolio-app:latest 590184014967.dkr.ecr.eu-west-1.amazonaws.com/portfolio-application:latest
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push 590184014967.dkr.ecr.eu-west-1.amazonaws.com/portfolio-application:latest
      - echo Writing image definitions file...
      - printf '[{"name":"portfolio-application","imageUri":"%s"}]' 590184014967.dkr.ecr.eu-west-1.amazonaws.com/portfolio-application:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
